//! Trait definitions for Supabase-syncable types.

use serde::Serialize;

/// Trait for types that can be synced to a Supabase table.
///
/// Implement this trait to define how your data maps to Supabase tables.
///
/// # Example
///
/// ```rust
/// use msg_supabase::prelude::*;
/// use serde::Serialize;
///
/// #[derive(Clone, Serialize)]
/// struct GameSession {
///     session_id: i64,
///     player_name: String,
///     score: u32,
/// }
///
/// impl SupabaseRow for GameSession {
///     fn table_name() -> &'static str {
///         "game_sessions"
///     }
///
///     fn primary_key_column() -> &'static str {
///         "id"  // Auto-generated by Supabase
///     }
///
///     fn unique_columns() -> &'static [&'static str] {
///         &["session_id"]  // Used for upsert conflict resolution
///     }
/// }
/// ```
pub trait SupabaseRow: Clone + Serialize + Send + Sync + 'static {
    /// The name of the Supabase table this type maps to.
    fn table_name() -> &'static str;

    /// The name of the primary key column (usually auto-generated by Supabase).
    ///
    /// This is used to retrieve the ID after insert and for updates.
    fn primary_key_column() -> &'static str;

    /// Column names that uniquely identify a row for upsert operations.
    ///
    /// When using `SaveMode::Update`, these columns are used in the
    /// `ON CONFLICT` clause for upsert operations.
    fn unique_columns() -> &'static [&'static str];

    /// Optional: Generate a unique sync key for deduplication.
    ///
    /// Override this if you want custom deduplication logic.
    /// By default, returns `None` (no deduplication by key).
    fn sync_key(&self) -> Option<String> {
        None
    }
}
